### ISSUE TITLE
pip upgrade doesn't really upgrade on 14.04

### ISSUE THREAD

**Issue by sjperkins** [radio-astro/docker-base#1]
```docker
FROM ubuntu:14.04
MAINTAINER gijs@pythonic.nl

ENV DEBIAN_FRONTEND noninteractive

# enable universe, multiverse, restricted with world wide mirrors
ADD apt.sources.list /etc/apt/sources.list
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y \
        software-properties-common \
        python-software-properties  \
        python-pip \
    && \
    add-apt-repository -y ppa:radio-astro/main && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# upgrade the pip package to the latest version
RUN pip install --upgrade pip
```

The last line in the Dockerfile does not in fact upgrade pip, because its a system package. The following [SO](http://stackoverflow.com/questions/38268074/how-should-i-upgrade-pip-on-ubuntu-14-04) suggests some options...

**Comment by gijzelaerr** [comment]
so first of all these docker images are not maintained anymore and replaced by the KERN ones:

https://hub.docker.com/r/kernsuite/base/

But you are right, for 14.04 this doesn't work:

```
root@472efa197393:/# pip --version
pip 1.5.4 from /usr/lib/python2.7/dist-packages (python 2.7)
root@472efa197393:/# pip install --upgrade pip
Downloading/unpacking pip from https://pypi.python.org/packages/9c/32/004ce0852e0a127f07f358b715015763273799bd798956fa930814b60f39/pip-8.1.2-py2.py3-none-any.whl#md5=0570520434c5b600d89ec95393b2650b
  Downloading pip-8.1.2-py2.py3-none-any.whl (1.2MB): 1.2MB downloaded
Installing collected packages: pip
  Found existing installation: pip 1.5.4
    Not uninstalling pip at /usr/lib/python2.7/dist-packages, owned by OS
Successfully installed pip
Cleaning up...
root@472efa197393:/# pip --version
pip 1.5.4 from /usr/lib/python2.7/dist-packages (python 2.7)
```

for Ubuntu 16.04 it works though:

```
root@5f89c9e9794a:/# pip --version
pip 8.1.1 from /usr/lib/python2.7/dist-packages (python 2.7)
root@5f89c9e9794a:/# pip install --upgrade pip
Collecting pip
  Downloading pip-8.1.2-py2.py3-none-any.whl (1.2MB)
    100% |################################| 1.2MB 690kB/s 
Installing collected packages: pip
  Found existing installation: pip 8.1.1
    Not uninstalling pip at /usr/lib/python2.7/dist-packages, outside environment /usr
Successfully installed pip-8.1.2
root@5f89c9e9794a:/# pip --version
pip 8.1.2 from /usr/local/lib/python2.7/dist-packages (python 2.7)
```

I recommend you switch to the KERN docker images.

**Comment by gijzelaerr** [comment]
if you are stuck with 14.04 I recommend you use the `get-pip.py` script:

https://pip.pypa.io/en/stable/installing/

**Comment by gijzelaerr** [comment]
since I like you a lot i made a kern-0 image:

https://github.com/kernsuite-docker/base/tree/0

it is currently building and should be soon ready as `kernsuite/base:0`

https://hub.docker.com/r/kernsuite/base/builds/bvwwvdjkoxcvb4xdautdmpt/

but probably you want to use `1` or `dev` anyway

**Comment by sjperkins** [comment]
@gijzelaerr Thanks! I logged this issue more because @SpheMakh's [Stimela](https://github.com/sphemakh/stimela) depends on radioastro. Not sure what the implications of upgrading all his cabbs would involve, perhaps @SpheMakh  can comment?

**Comment by sphemakh** [comment]
I have to switch to kernsuite images soon. I'll do this this week.
